### ISSUE TITLE
Launch script builds desktop app on Termux

### ISSUE THREAD

**Issue by RaghavPrabhakar66** [flowdriveai/flowpilot#10]
`flowinit` checks what device its running on, and acts accordingly. Though the device is `Android` is checked by `ANDROID_ROOT` [flag](https://github.com/flowdriveai/flowpilot/blob/master/common/system.py#L17).
But in the doc, we add `ANDROID_DATA` flag. <br>

This causes to script to run gradle on smartphone.

**Comment by MankaranSingh** [comment]
Fixed
