### ISSUE TITLE
Pixel 4A hangs with logo on startup

### ISSUE THREAD

**Issue by WriteCodeEveryday** [flowdriveai/flowpilot#19]
Installed the flowpilot APK for testing, app starts but hangs with the logo.

I just wanted to see what the benchmark said.

![Screenshot (Jan 1, 2023 12_38_33 PM)](https://user-images.githubusercontent.com/1066583/210179967-4476a6be-72b5-49c4-b727-482517d2c68b.png)

**Comment by WantGuns** [comment]
It looks like you didn't set up Termux. Please follow the wiki -- https://github.com/flowdriveai/flowpilot/wiki/Installation#installation-for-android
