### ISSUE TITLE
failed to install and run on desktop

### ISSUE THREAD

**Issue by jcl2023** [flowdriveai/flowpilot#26]
I follow installation instructions below and got erros at step 3, scons:

1) cd ~/flowpilot
2) pipenv shell
3) scons

(flowpilot) root@legion:~/flowpilot# scons
scons: Reading SConscript files ...
ModuleNotFoundError: No module named 'Crypto':
  File "/root/flowpilot/SConstruct", line 175:
    SConscript(['panda/board/SConscript'])
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/root/flowpilot/panda/board/SConscript", line 132:
    certs = [get_key_header(n) for n in ["debug", "release"]]
  File "/root/flowpilot/panda/board/SConscript", line 132:
    certs = [get_key_header(n) for n in ["debug", "release"]]
  File "/root/flowpilot/panda/board/SConscript", line 102:
    from Crypto.PublicKey import RSA

Also do "pip install Crypto", but the issue still exists.

Please help

**Comment by MankaranSingh** [comment]
did you run `get_dependencies.sh` after `pipenv shell` ?

**Comment by jcl2023** [comment]
After exit pipenv and re-enter again, scons compiles OK now.
Not sure why.
How to run it and what to expect to see on the screen? My PC has webcam attached to it.

Thanks,

**Comment by MankaranSingh** [comment]
in `launch_flowpilot.sh`, set camera_source="0" to get webcam working.

**Comment by jcl2023** [comment]
Works OK with launch_flowpilot.sh. Waiting for token from you.
How long will it take to send token out?

**Comment by MankaranSingh** [comment]
backend is down at the moment, you can use this python script to skip login
```
from common.params import Params
Params().put("UserID", "000000")
```
and restart

**Comment by jcl2023** [comment]
Where should I add this script?

Thanks,
