### ISSUE TITLE
install pip<=22.3

### ISSUE THREAD

**Issue by 0312birdzhang** [flowdriveai/flowpilot#31]
Otherwise `pip install pycapnp==1.0.0 --install-option="--force-system-libcapnp" > /dev/null 2>&1` will not working well, as on pip 23, they [deprecate `--install-options` argument](https://github.com/pypa/pip/pull/11858)

**Comment by RaghavPrabhakar66** [comment]
It works without `--install-options` also, so I think we can close this issue.
