### ISSUE TITLE
Bleeding Edge 0.2.3 - clocksd & laikad crash

### ISSUE THREAD

**Issue by Narolth** [flowdriveai/flowpilot#34]
**Describe the bug**
Bleeding Edge 0.2.3 (updated with repo on 2023/06/26
![Screenshot_20230626-181225](https://github.com/flowdriveai/flowpilot/assets/31808960/2075cc5a-0441-436f-bc70-822003b61973)
![Screenshot_20230626-181232](https://github.com/flowdriveai/flowpilot/assets/31808960/b8177f9c-8ebe-4657-972c-71bed2d615fd)
) 
Error when starting Flow Pilot:
[clocksd] clocksd: cereal/messaging/socketmaster.cc:204: PubMaster::PubMaster(const std::vector<const char*> &): Assertion `socket' failed.

Followed by a laikad error after "waiting for CAN messages...

**To Reproduce**
./launch_flowpilot.sh
launch flowpilot 0.2.3 apk

**Expected behavior**
To not crash :D

**Platform Details**

Android :
 - android version: 13
 - manufacturer: Google
 - model: Pixel 6 Pro
 - rooted ? : Yes
 - using root or non-root env ? root env

**Additional context**
Attached screen shots

**Comment by MankaranSingh** [comment]
Hey, I was not able to reproduce the error, this could happen because the submodule was not updated. 
Can you check by running `git submodule update` ? and making sure the git commits of submodule match

**Comment by Narolth** [comment]
I switched to master after this to see if I could get away with copying the gm values.py from bleeding to master, however I just switched back to bleeding edge. 

I'll test again after work:

`root@localhost:~# ./switchBranches.sh
Please select the branch:
 1. backend_auth_integration
 2. bleeding-edge
 3. car-interface-revert
 4. community
 5. external_cam
 6. feat_uploader
 7. fix_java_http_client
 8. flowinit-refactor
 9. installation-simplify
 10. locationd-integration
 11. loggerd
 12. loggerdv2
 13. master
 14. navd
 15. new_model
 16. path-fixing
 17. release
 18. reports
 19. sentry-integration
 20. subaru-fix
 21. tnn-model
 22. updadte-to-latest

Enter your choice (1-22): 2
Warning: You have local changes that may be overwritten.
Do you want to stash your changes? (y/n): n
Executing: git reset --hard
HEAD is now at ffafaa1 fix sim
Warning: There are still local changes. Continuing without stashing.
Warning: You have local changes that may be overwritten.
Do you want to stash your changes? (y/n): n
Executing: git reset --hard
HEAD is now at ffafaa1 fix sim
Executing: git fetch
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), 346 bytes | 15.00 KiB/s, done.
From https://github.com/flowdriveai/flowpilot
 * [new branch]      car-interface-revert -> origin/car-interface-revert
Executing: git checkout bleeding-edge
M       cereal
M       laika_repo
M       opendbc
M       panda
M       rednose_repo
Switched to branch 'bleeding-edge'
Your branch is up to date with 'origin/bleeding-edge'.
Executing: git pull origin bleeding-edge
From https://github.com/flowdriveai/flowpilot
 * branch            bleeding-edge -> FETCH_HEAD
Already up to date.
Executing: git submodule update
Submodule path 'cereal': checked out 'b686e8e8547d9e6ca2229081715f89d26972df65'
Submodule path 'laika_repo': checked out 'e932f32ab921ed09ba6e304990574693d8ca5199'
Submodule path 'opendbc': checked out 'a169926a3f2514ea463baac6d5af1b0dde648616'
Submodule path 'panda': checked out '2da9b8d17319be80d48402eb73bb67a36c001d30'
Submodule path 'rednose_repo': checked out '9dbb178de6de8b58a8b98b59e4db072133021f5b'
/root`

**Comment by Narolth** [comment]
I switched back to Bleeding Edge. First launch took a while as always, looked like scons was building, then the apk crashed on launch.
```
~ $ sudo login-flowpilot-root
root@localhost:~# ls
flowpilot  switchBranches.sh  values.py
root@localhost:~# ./switchBranches.sh
Please select the branch:
 1. backend_auth_integration
 2. bleeding-edge
 3. car-interface-revert
 4. community
 5. external_cam
 6. feat_uploader
 7. fix_java_http_client
 8. flowinit-refactor
 9. installation-simplify
 10. locationd-integration
 11. loggerd
 12. loggerdv2
 13. master
 14. navd
 15. new_model
 16. path-fixing
 17. release
 18. reports
 19. sentry-integration
 20. subaru-fix
 21. tnn-model
 22. updadte-to-latest

Enter your choice (1-22): 2
Warning: You have local changes that may be overwritten.
Do you want to stash your changes? (y/n): n
Executing: git reset --hard
HEAD is now at 674e0ec use NOSENSOR by default
Warning: There are still local changes. Continuing without stashing.
Warning: You have local changes that may be overwritten.
Do you want to stash your changes? (y/n): n
Executing: git reset --hard
HEAD is now at 674e0ec use NOSENSOR by default
Executing: git fetch
Executing: git checkout bleeding-edge
Already on 'bleeding-edge'
Your branch is up to date with 'origin/bleeding-edge'.
Executing: git pull origin bleeding-edge
From https://github.com/flowdriveai/flowpilot
 * branch            bleeding-edge -> FETCH_HEAD
Already up to date.
Executing: git submodule update
/root
```

I rebooted the phone, and launched the apk (not premium), it launched, initialized, and began calibration, it completed calibration, but the path and lane indicators never showed up. 

During driving attempting to engage resulted in ` openpilot Unavailable Controls Mismatch `

The attached photos are in sequential order while running some errands. I noticed that it looked lie there were line markers or somethign strange in the lower left and right corners of the screen.

What else would be helpful?

![Screenshot_20230629-203110](https://github.com/flowdriveai/flowpilot/assets/31808960/52cad4cc-bf07-4183-b439-f5846814ece8)
![Screenshot_20230629-203226](https://github.com/flowdriveai/flowpilot/assets/31808960/f436065c-1ad1-4eaa-83cd-bc9dcf9b74e6)
![Screenshot_20230629-203316](https://github.com/flowdriveai/flowpilot/assets/31808960/29a2c752-7346-4fff-b4fd-834811e97fb8)
![Screenshot_20230629-204540](https://github.com/flowdriveai/flowpilot/assets/31808960/45af7337-1a23-4072-a3fc-ddaa52675c62)
![Screenshot_20230629-204830](https://github.com/flowdriveai/flowpilot/assets/31808960/8beafefe-64fc-4942-8b21-d313357da392)
![Screenshot_20230629-205149](https://github.com/flowdriveai/flowpilot/assets/31808960/3acc9d28-d76f-4bc5-8a50-4849cc9d92fa)
![Screenshot_20230629-205157](https://github.com/flowdriveai/flowpilot/assets/31808960/07db7e68-4165-4320-b67b-def6ac2958a7)
![Screenshot_20230629-205834](https://github.com/flowdriveai/flowpilot/assets/31808960/34247051-8051-447d-8ce4-d62150fefd8d)

**Comment by Narolth** [comment]
Also I was going to see if the issue happens in the premium app, but have not tested yet, all testing so far was in the standard apk.

**Comment by Narolth** [comment]
Confirmed I can reproduce on both a Pixel 6, and Samsung S20 if that's helpful.

**Comment by Narolth** [comment]
I added the magisk opencl module provided by [reekotubbs](https://github.com/reekotubbs) for my pixel 6 pro, and the latency super low, however same issues for clocksd & laikad crash

**Comment by Narolth** [comment]
@MankaranSingh, given that you cannot reproduce, and it's for a Chevrolet Bolt, is there any additional information I can gather that would be helpful? I've setup a laptop with ubuntu 20.04, happy to pull logs, join a screen share etc, whatever would be helpful.

**Comment by myhdh10** [comment]
Hi, I got those problem same as @Narolth.
I did an update of submodule.

**Comment by pubg1** [comment]
The port for the 'clocks' PubMaster is always shown as in use every time it starts up.     It is this issue that causes the 'clocks' service to crash.

**Comment by Paperboypaddy** [comment]
I was also able to confirm this issue on my 7T but when running dummy publishers.

**Comment by pubg1** [comment]
When the FP's UI is running but 'flowinit' is not, ports 5140 and 5141 are still occupied. These two ports are allocated to the 'clocksd' and 'laikad' services in the program, which is the reason why these two services cannot start

**Comment by MankaranSingh** [comment]
found the issue, releasing a fix

**Comment by MankaranSingh** [comment]
apologies for the delay, please redownload and install the apk from here https://github.com/flowdriveai/flowpilot/releases/tag/v0.2.3
Please note, bleeding edge is still in very alpha development. master branch is stable for use.

**Comment by pubg1** [comment]
I installed the latest premium apk, and the 'clocksd' and 'laikad' services have returned to normal. However, an error occurred when running 'dummy_publishers'.
![image](https://github.com/flowdriveai/flowpilot/assets/34304324/fe89fcd3-b59e-424f-a30e-3878f4d2c718)

**Comment by pubg1** [comment]
> apologies for the delay, please redownload and install the apk from here https://github.com/flowdriveai/flowpilot/releases/tag/v0.2.3 Please note, bleeding edge is still in very alpha development. master branch is stable for use.

![image](https://github.com/flowdriveai/flowpilot/assets/34304324/5a85c3bc-6106-4347-b73d-b4c40f10a347)
I installed the latest premium apk, and the 'clocksd' and 'laikad' services have returned to normal. However, an error occurred when running 'dummy_publishers'

**Comment by Narolth** [comment]
Will test with my Bolt and update afterward, thanks @MankaranSingh !

**Comment by Narolth** [comment]
The reason this issue was opened appears to be resolved now thank you!
![image](https://github.com/flowdriveai/flowpilot/assets/31808960/6cdd9e95-dc01-4888-a9e5-2a7c62a09214)
![image](https://github.com/flowdriveai/flowpilot/assets/31808960/241cede9-baac-419f-a78f-dca4280f1267)
![image](https://github.com/flowdriveai/flowpilot/assets/31808960/60327fb3-9a2f-41e2-a344-5e0929fe10b5)
