### ISSUE TITLE
Error: sentry-sdk 1.10.1 has requirement that is not met during new install

### ISSUE THREAD

**Issue by Narolth** [flowdriveai/flowpilot#36]
**Describe the bug**
During install on Android 13 with root, after running step 9: install-flowpilot-android
"Error: sentry-sdk 1.10.1 has requirement urllib3>=1.26.11; python_version>=3.6, but you'll have urllib3 1.25.8 which is incompatible"

**To Reproduce**
uninstall termux & FP, and then re-install

**Expected behavior**
No error

**Platform Details**
Android :
 - android version: 13
 - manufacturer: Google
 - model:  Pixel 6 pro
 - rooted ?  : Yes
 - using root or non-root env, root environment

**Additional context**
Attached screen shot:
![image](https://github.com/flowdriveai/flowpilot/assets/31808960/2427a028-9cd6-45b9-b318-ec5921ad9c9f)

**Comment by MankaranSingh** [comment]
it's actually a warning. Shouldnt affect the working.

**Comment by Narolth** [comment]
Gotcha, I don't think I've seen it interfere, just reporting it as I saw it, thanks!
