### ISSUE TITLE
Tried in Dashcam Mode, the banner takes half of the screen. Is this a bug or by design?

### ISSUE THREAD

**Issue by gitercn** [flowdriveai/flowpilot#43]
**Describe the bug**
My car is not in the supported list and I don't have the hardware to connect to a car, but I wanted to try out this in Dashcam Mode. I followed the installation guide and successfully installed and launched the app. However, the Dashcam Mode green banner takes half of the screen, makes the lane lines hard to see.  Is this a bug or by design?

![Screenshot_ai flow android](https://github.com/flowdriveai/flowpilot/assets/53464166/861e85ba-586f-4b6d-98f3-c8b11fdb8b37)

**To Reproduce**
1. Followed the installation guide to install the premium version.  
2. Uncommitted the line `#export FINGERPRINT="HONDA CIVIC 2016"` in `launch_flowpilot.sh` to hardcoding figureprinting since my car is not supported.
3. Set USE_SNPE="1" in launch_flowpilot.sh to enable SNPE.
4. Launched flowpilot and opened `python scripts/dummy_publishers.py`.

**Expected behavior**
Make the Dashcam Mode banner smaller in able to view the lane predictions.
Also, the speed shows on the screen kept at 72 kmph. I guess the speed is from the dummy_publishers.py? Is it possible to get real speed from phone's GPS?

**Platform Details**

Android :
 - android version: 13
 - manufacturer: Redmi
 - model:  K40
 - rooted ?  : yes
 - using root or non-root env ? root

**Comment by MankaranSingh** [comment]
its expected behavior actually. you can remove the `dascam event` in controlsd.py to remove this banner.

**Comment by Expro** [comment]
Yeah, same issue on PC with additional info on "car unrecognized". It would be great to have and X or toggle to disable those messages as they make it completely unusable.

**Comment by Expro** [comment]
Also, removal of "dashcam event" and "unrecognized car" event spawns "Flowpilot not available" message, which also takes half of screen...

**Comment by mohit-deepgrid** [comment]
Do we have to reinstall after making changes in the .java files for the changes to reflect?

**Comment by MankaranSingh** [comment]
> Do we have to reinstall after making changes in the .java files for the changes to reflect?

you will need to build the android apk again. Setup the project on desktop (check wiki) then rebuuild the apk as you would normally do for an android project.
