### ISSUE TITLE
White and blue artifacts

### ISSUE THREAD

**Issue by dingyifei** [flowdriveai/flowpilot#5]
Pixel 6A

Android 12

Tnn-model

Symptom: blue horizontal lines(multiple pixel) and white triangular geometry occasionally show up.

**Comment by MankaranSingh** [comment]
The white triangle is lead car detection. Its a feature not a bug. 
Need to look at blue glitch. Its probably something wrong with path visualisation.

**Comment by MankaranSingh** [comment]
Seems to ve fixed in master branch. High CPU usage can also cause this artifact sometimes.
