### ISSUE TITLE
SSL Error Unable to Properly Install Python3.9 Environment

### ISSUE THREAD

**Issue by hadysalama** [flowdriveai/flowpilot#52]
**Describe the bug**
When running sudo add-apt-repository ppa:deadsnakes/ppa using install-flowpilot-android in the virtual machine I always get an  
ssl.sslerror malloc failure ssl.c:3093
Then when the script trys to install python3.9 using apt it fails.

My workaround: 
Reinstalled openssl,
Readded certificates,
Connected to WiFi with a basic DNS and default network settings,
Successfully installed python3.9 on my own by compiling from downloaded source using GCC and make with SSL and made it default.
When pip installing all the necessary python requirements got more SSLs errors.
pip install error: https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi

Tried fixing pip but nothing worked.

**To Reproduce**
Run installation instructions on an older Android device. Execute sudo install-flowpilot-android

**Expected behavior**

Flowpilot successfully installed.

**Platform Details**

Android :
 - android version: 7 (technically unsupported)
 - manufacturer: Samsung
 - model: Galaxy J7
 - rooted ?: No
 - using root or non-root env ? non-root env

**Additional context**
I have a couple questions? Is the SSL error due an improperly configured Ubuntu VM or is it due to the version of Android? Does the flow-pilot apk totally reject unsupported versions of Android? The apk kept crashing after installing but the environment was not running properly due to the error above.

**Comment by MankaranSingh** [comment]
Are you using termux from fdroid or playstore ? 
Even if you get the termux env working, the apk is still not going to work because it only supports android>=10

**Comment by hadysalama** [comment]
Hey thanks for the response, I'm using termux from the link in the instructions not the store. The APK wouldn't work so I'm going to get an android 12 device. I mainly did this to test out the installation before buying anything. In terms of the virtual machine openssl handshakes work in Termux on the actual device (Samsung Galaxy J7) but they consistently fail inside the ubuntu environment. Do you have any idea about how to fix this? I only have 1.8GB of memory available on the Galaxy J7 so I was thinking when openssl returns a malloc error that it's running out of memory but again openssl handshakes work on the device itself outside of the VM.

**Comment by MankaranSingh** [comment]
Hmm, this should be reported to the `termux-proot` repo they maintain the non root env (proot). Older android version could likely be a cause.
