### ISSUE TITLE
Android installation stops and shows error ..could not locate python3.9...

### ISSUE THREAD

**Issue by prtpilot8553** [flowdriveai/flowpilot#55]
Android installation in termux is stopped and it shows the error could not locatre python3.9...

However python3.11 is successfully installed by the steps mentioned in the wiki installation procedure.. 

Is there any sollution

I am using un rooted android 12 and Redmi Note 9.

**Comment by MankaranSingh** [comment]
so ubuntu-proot distro updated their ubuntu from jammy to mantic,
you can try using an older version of ubuntu distro 
https://github.com/termux/proot-distro/issues/202

here are the distribution links

**Comment by mbilalai** [comment]
I'm facing the same issue on android 11.

**Comment by YJBarman** [comment]
I am also facing same issue on android 12.
After I executed this "install-flowpilot-android"
E: Unable to locate package python3.9
E: Couldn't find any package by glob 'python3.9'
E: Unable to locate package python3.9-dev
E: Couldn't find any package by glob 'python3.9-dev'
E: Unable to locate package python3.9-distutils
E: Couldn't find any package by glob 'python3.9-distutils'
Although I installed python3.9.

**Comment by MankaranSingh** [comment]
Should be fixed by #58

**Comment by Ammark747** [comment]
error: 8006 bytes of body are still expectedfetch-pack: unexpected disconnect while reading sideband packet                         fatal: early EOF                            fatal: fetch-pack: invalid index-pack output/bin/install-flowpilot-android: line 58: cd: /root/flowpilot: No such file or directory /bin/install-flowpilot-android: line 62: ./get_dependencies.sh: No such file or directory

**Comment by MankaranSingh** [comment]
That seems like your internet issue. Reopen another issue if it still persists.

**Comment by Ammark747** [comment]
How to solve this
