### ISSUE TITLE
wget command is not working

### ISSUE THREAD

**Issue by anilkumarkatta204** [flowdriveai/flowpilot#66]
**Describe the bug**
Following both commands unable to download the contents:

wget -q https://raw.githubusercontent.com/flowdriveai/flowpilot/master/scripts/flowpilot-setup-env-android
wget -q https://raw.githubusercontent.com/flowdriveai/flowpilot/master/scripts/install-flowpilot-desktop

**To Reproduce**
run above commands in termux or cli of the ubuntu

**Expected behavior**
expection to get downloaded folders for flowpilot

**Platform Details**
Ubutnu

Android :
all

**Additional context**

![image](https://github.com/flowdriveai/flowpilot/assets/4068191/1841270c-4c73-4e12-87bf-3c5e49303bb0)

**Comment by RaghavPrabhakar66** [comment]
I am able to download, looks like a network issue. Any chance you on Jio Network as I have faced raw.githubcontent.com unaccessible. More info on https://github.com/orgs/community/discussions/42655.

**Comment by anilkumarkatta204** [comment]
> I am able to download, looks like a network issue. Any chance you on Jio Network as I have faced raw.githubcontent.com unaccessible. More info on https://github.com/orgs/community/discussions/42655.

Yes, I was using JIO Network. Also, on my surprise termux (which worked ok on my mobile yesterday) is not working for pkg upgrade as well, says bad internet connectivity.  looks banned ? i tried the suggeesions from the above discussion link nothing working.

I love to try this software on my car

**Comment by anilkumarkatta204** [comment]
solved after using Airtel mobile internet, this is an environment issue rather product issue, hence closing the case.

**Comment by anilkumarkatta204** [comment]
solved after using Airtel mobile internet, this is an environment issue rather product issue, hence closing the case.
