### ISSUE TITLE
What`s the version of supercombo.onnx

### ISSUE THREAD

**Issue by eatfishfish** [flowdriveai/flowpilot#71]
Hi, can you tell me the version of supercombo.onnx? openpilot 0.8.16 or 0.9.1?
Can we use the newest version openpilot`s supercombo.onnx?

**Comment by MankaranSingh** [comment]
the master branch is using 0.8.x, the premium branch has support for 0.9.x (models with dual camera input and nav). Newer models can be added but the code might need some modifications to adapt if the model outputs/inputs are different

**Comment by eatfishfish** [comment]
> the master branch is using 0.8.x, the premium branch has support for 0.9.x (models with dual camera input and nav). Newer models can be added but the code might need some modifications to adapt if the model outputs/inputs are different

Great! Thank you. Keep on.
