### ISSUE TITLE
Update Repo to say it is ABANDONED and go to my FAQ for more recent information!

### ISSUE THREAD

**Issue by phr00t** [flowdriveai/flowpilot#77]
The "official" flowpilot repo has been abandoned and does not work out-of-the-box for any platform, nor is it anywhere near as reliable as modern openpilot if you do get it working. The original developer was an amazing founder and made a great foundation for running open pilot on Android, but like many things, the dream was bigger than what became realized here.

I've forked this project and got it working on my LG G8, which works amazingly well. I had to rewrite and redesign significant sections to accomplish this. I've got my fork working with the latest thneed models too, neat!

Compatibility took a hit though, as I can say only LG G8's work (OnePlus 7T would be the next closest thing). I had to pair down the project to realistically deliver something useable and up-to-date. If you are going to continue working on this project, I highly recommend you start from my fork.

https://github.com/phr00t/flowpilot/wiki/FlowPilot:-FAQ

**Comment by MankaranSingh** [comment]
Added, to readme. I love your work and support. Flowpilot's main goal has always been to enable wide support for all devices. Like LG G8, community can finetune it for other devices as well. 
I'd like if you make your direction more device independent. It shouldn't be much harder. 
Thanks
