### ISSUE TITLE
houp[op=09lonbiu(O)9087_+lobfP)87+{}:

### ISSUE THREAD

**Issue by GTGPLAYZ** [flowdriveai/flowpilot#81]
**Describe the bug**

**To Reproduce**
optional 

**Expected behavior**

**Platform Details**
Desktop:
  - linux distro
  - using gpu / cpu ?

Android :
 - android version: for eg, 12
 - manufacturer: for eg, Redmi
 - model:  for eg, Note 9 pro
 - rooted ?  :
 - using root or non-root env ? 

**Additional context**

**Comment by RaghavPrabhakar66** [comment]
@GTGPLAYZ ??
